# Basics of Julia programming Language  
### Notebook containing the lectures of Martin D. Haas. They can be founded at the following link: https://www.matecdev.com/posts/julia-tutorial-science-engineering.html#is-the-julia-language-free

The following lines contains codes and text explaining the basics of the Julia language, then, this informations will be used for coding.

Julia is based on the Packages, they can be easely installed from the REPL. For example, let's install the Linear Algebra package, just write:  
`import Pkg; Phg.add("LinearAlgebra")`  
and then, at the beginning of the code:  
`using LinearAlgebra`

The packages can be founded in the official Julia web site, or even the following two links are useful:  
- Julia Observer: https://juliaobserver.com/packages  
- Julia Packages: https://juliapackages.com/

## REPL initializing and functionalities
This is true for .jl files, not for Jupyter notebook.  
Before to start coding anything, open the VSCode terminal, type `Julia: Start REPL`, this will start the REPL. From now on, the REPL can be used in 4 ways:
- Typing directly some commands;
- ? for access the help mode, name of functions can be written after '?' to get some documentation;
- ; for access the shell mode, this allows you to navigate over the directories;
- ] for access the package mode, to install packages.


### Run only part of the whole code
There are few short cut for running just part (or lines) of the whole code:
- Ctrl+Enter: Run a line;
- Alt+Enter: Run a block (selected text);
- Shift+Enter: Run a cell (delimed by ## like in Matlab)

To run the whole file just type `Julia: Execute File in REPL`, or just click 'run' in the upper-right corner and select 'Execute File in REPL'

Julia adopts the Unicode Math Symbols for greek letters and so on just typing them as in latex, hereinafter an example. This make the code fancy and easier to read.

In [1]:
θ = 5
α = 11
π
# ecc

π = 3.1415926535897...

Julia Should show the autocompletions while typing, It could happen that it do not. In that case, just press `Ctrl+Space`

# Shortcut list
For appearing the complete list of shorcuts just type `Ctrl + K` and then `Ctrl + S`.

# Variables types

## Numerical variables
It is important to know there is a Hierarchy into the numerical variables, that have to be seen as follows: it is straighforward to convert numbers from lower to higher hierarchical levels, it is not from higher to lower levels. The Hierarchy is depicted by the image:  

![Hierarchy](images/Number_Hierarchy.PNG)

Some examples are reported in the following cell

In [2]:
# From integer to floating point numbers: lower => higher
Float64(2) # 2.0 double precision
Float32(2) # 2.0f0 single precision
Float16(2) # Float16(2.0) half precision

Float16(2.0)

In [3]:
# From floating point numbers to integer: higher => lower
Int64(2.0)          # 2
# Int64(2.4)          # error
floor(Int64,2.4)    # 2
ceil(Int64,2.4)     # 3

3

### Divisions 
By definition, dividing two integers we obtain a float64, we can truncate the division at the integer using the `div()` function (also can be used `÷`) or return the remainder (resto) with the `rem()` (also can be used `%`).

In [4]:
a = 1/2     # 0.5, Float64
div(10,3)   # 3
÷(10,3)     # 3
rem(10,3)   # 1
%(10,3)     # 1

1

### Integers vs Float
assigning `a = 2`, julia automatically assign 'Int64' to `a`, that after `2^{64}` goes overflow. Leading to unexpected results for the expression `1/a^64`

In [5]:
a = 2
b = 1/a^64

Inf

Just replacing the `Int64` with the `Float64` in one of the following way the problem is fixed.

In [6]:
a = 2.0
b = 1/a^64

5.421010862427522e-20

In [7]:
a = 2
b = (1/a)^64

5.421010862427522e-20

## Boolean Variables
The boolean variables are of course `true` and `false`, to which we can apply some conditions:

### Locigal Operators
- And: `&&` it check the first condition fisrt, than the second. It does not even check the second condition if the first is `false`;
- Or: `||` as the 'and' condition, if the first condition is `true` it does not even check the second.
- Not: `!` it have to be put before the expression, return the opposite of the expression (example: `if x!=0 ...` means 'if x is different than 0...').


### Logical to numbers
The boolean variables can be used also as integers, in fact `true==1` and `false==0`

In [8]:
true + true

2

In [9]:
true

true

In [10]:
true + false

1

# String concatenation and formatting

Very important information: in Julia there is a distinction between.
- Character: `char` defined by `'...'`;
- String: `string` defined by `"..."`, it contains multible characters.  

Both the following structures are used to concatenate strings

In [11]:
"Hello " * "wor" * "ld"
string("Hello ", "wor", "ld")

"Hello world"

### Convert Numbers to String
There are 3 main ways:
- Using `string` function, probably the easiest and the most intuitive, not the cheapest;
- Using string interpolation, the cheapest, used especially for writing long strings;
- Using the C-style `Printf` package, especially used to control the formats.

In [12]:
using Printf

In [13]:
string(1/7, " is a rational number")
"$(1/7) is a rational number"

"0.14285714285714285 is a rational number"

In [14]:
@sprintf("%.4f is a rational number", 1/7)

"0.1429 is a rational number"

Qui di seguito sono riportati altri comandi che possono essere utili nell'utilizzo dei notebook

In [15]:
st1 = string(1/7, " is a rational number")
st2 = "$(1/7) is a rational number"
st3 = @sprintf("%.4f is a rational number", 1/7)

"0.1429 is a rational number"

In [16]:
println(string(1/7, " is a rational number"))
println("$(1/7) is a rational number")
println(@sprintf("%.4f is a rational number", 1/7))

0.14285714285714285 is a rational number
0.14285714285714285 is a rational number
0.1429 is a rational number


In [17]:
@show string(1/7, " is a rational number")
@show "$(1/7) is a rational number"
@show @sprintf("%.4f is a rational number", 1/7)

string(1 / 7, " is a rational number") = "0.14285714285714285 is a rational number"
"$(1 / 7) is a rational number" = "0.14285714285714285 is a rational number"
#= c:\Users\utente\Documents\JULIA\Julia_course\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_X50sZmlsZQ==.jl:3 =# @sprintf("%.4f is a rational number", 1 / 7) = "0.1429 is a rational number"


"0.1429 is a rational number"

In [18]:
# Example of long string concatenation
rmse = 1.5; mse = 1.1; R2 = 0.94
"Our model has a R^2 of $(R2), rmse of $(rmse), and mse of $(mse)"

"Our model has a R^2 of 0.94, rmse of 1.5, and mse of 1.1"

# For loops

The simplest way to perform a for loop is the following:

In [19]:
x=0
for k in 1:100000
    x = x + (1/k)^2
end
println("x = $x")

x = 1.6449240668982423


### Nested loops
Most of the real cases are actually nested loops, that can be performed in the simple way:

In [20]:
for i in 1:3
    for j in 1:3
        print("i=", i, " j=", j, "\n")
    end
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


The same can be done with a slighly different sintax, more compact especially for more than 2 loops (the symbol 'appartenente' is written in julia as `\in`)

In [21]:
for i in 1:3, j in 1:3
    print("i=", i, " j=", j, "\n")
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


In [22]:
for i ∈ 1:3, j ∈ 1:3
    print("i=", i, " j=", j, "\n")
end

i=1 j=1
i=1 j=2
i=1 j=3
i=2 j=1
i=2 j=2
i=2 j=3
i=3 j=1
i=3 j=2
i=3 j=3


### Break statement
It is used to break a for loop before the ending of all the iterations, as in Matab

### Continue statement
It is used to skip the current iteraion of a for loop and continue from the following, example:

In [23]:
numbers = randn(100)
somma = 0
for k in numbers
    if (k==0) continue end
    somma = somma + 1/k
end
println(@sprintf("numbers (first) = %.5f", numbers[1]))
println("sum = $somma")

numbers (first) = 0.34417
sum = -28.574013778310057


# Functions
In julia functions are used to gain computational speed, in fact, each of the most expensive parts of the code should be placed into a function.
### Defining functions
A function can be defined in the two following ways (the second is one line). Once the function is defined and executed, it can be called iven from the REPL, there is no need to assign a variable to the result of the function.

In [24]:
# "Traditional" for loop
function sum_zeta_equivalent(s, nterms)
    x = 0.0
    for n in 1:nterms
        x = x + 1/n^s
    end
    return x
end

# "Smarter" for loop
function sum_zeta(s, nterms)
    x = 0.0
    for n in 1:nterms
        x += 1/n^s
    end
    return x
end

# One line function (for loop)
sum_zeta_oneline(s::Int64, nterms::Int64) = sum((1.0 / n)^s for n in 1:nterms)
#methods(sum_zeta_oneline)

sum_zeta_oneline (generic function with 1 method)

In [25]:
println("sum_zeta(2, 100000) = ", sum_zeta(2, 100000))
println("sum_zeta_equivalent(2, 100000) = ", sum_zeta_equivalent(2, 100000))
println("sum_zeta_oneline(2, 100000) = ", sum_zeta_oneline(2, 100000))

sum_zeta(2, 100000) = 1.6449240668982423
sum_zeta_equivalent(2, 100000) = 1.6449240668982423
sum_zeta_oneline(2, 100000) = 1.6449240668982423


### Functions with optional input
Can be useful to define a default value of certain input, so that in can either expressed when calling the function or not, as follows:

Note there is a difference between the two:  
1. function 1 is defined with a comma between the two arguments and the second has a default value, in this case, the default value CANNOT be modified when calling the function;
2. function 2 is defined with a semicolon between the two arguments and the second has a default value, in this case, the default value CAN be modified when calling the function. The position of the calling of the pre-set value is not important, is the name the govern the call. In the calling just use commas. 


In [26]:
# function 1
sum_zeta_oneline(s, nterms = 100000) = sum((1.0 / n)^s for n in 1:nterms)
# methods(sum_zeta_oneline)

sum_zeta_oneline (generic function with 3 methods)

In [27]:
println("sum_zeta_oneline(2, 100000) = ", sum_zeta_oneline(2))
println("sum_zeta_oneline(2, 10) = ", sum_zeta_oneline(2, nterms = 10))
# if it works is because the cell below is already executed

sum_zeta_oneline(2, 100000) = 1.6449240668982423


MethodError: MethodError: no method matching sum_zeta_oneline(::Int64; nterms::Int64)
This method may not support any kwargs.

Closest candidates are:
  sum_zeta_oneline(::Int64, !Matched::Int64) got unsupported keyword argument "nterms"
   @ Main c:\Users\utente\Documents\JULIA\Julia_course\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_X66sZmlsZQ==.jl:20
  sum_zeta_oneline(::Any, !Matched::Any) got unsupported keyword argument "nterms"
   @ Main c:\Users\utente\Documents\JULIA\Julia_course\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y103sZmlsZQ==.jl:2
  sum_zeta_oneline(::Any) got unsupported keyword argument "nterms"
   @ Main c:\Users\utente\Documents\JULIA\Julia_course\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y103sZmlsZQ==.jl:2


In [28]:
# function 2
sum_zeta_oneline(s; nterms = 100000) = sum((1.0 / n)^s for n in 1:nterms)
# methods(sum_zeta_oneline)

sum_zeta_oneline (generic function with 3 methods)

In [29]:
println("sum_zeta_oneline(2, 100000) = ", sum_zeta_oneline(2))
println("sum_zeta_oneline(2, 10) = ", sum_zeta_oneline(2, nterms = 10))

sum_zeta_oneline(2, 100000) = 1.6449240668982423
sum_zeta_oneline(2, 10) = 1.5497677311665408


### Functions with multiple output
Just put more than one variables after the `return` statement, separated by a comma.  
The calling phase can be any, all the output can be called in a single structure (immutable) and then separeted, or directly stored in more variables.

### Functions which modify the input
Since Julia doesn't pass a copy of the input array but the array itself, the notation when a function modify at least one of their input consists in putting a `!` after the name of the function.  
NB: julia mutates only the mutable objects, if we try tu mutate a structure into a function, then it will be modified only inside it, not outside, as happend for the arrays.

### Anonimous functions
Can happen that we don't want to store a function that have to be passed as input of an other function (maybe it's easy and it's not convenient to store it), than a function can be defined without saving it. Let's see the example:

In [30]:
# This function finds the root of a function f using the secant method
# f: function to find the root of
function secant(f,a,b,rtol,maxIters)
    iter = 0
    while abs(b-a) > rtol*abs(b) && iter < maxIters
        c,a = a,b
        b = b + (b-c)/(f(c)/f(b)-1)
        iter = iter + 1
    end
    return b
end

secant (generic function with 1 method)

In [31]:
ϕ = secant(x -> x^2 - x - 1, 1, 2, 1e-15, 10)
# The function here is x -> x^2 - x - 1
println("ϕ = $ϕ")

ϕ = 1.6180339887498947


### Storing function in separate files
We can write a separate .jl file (example: functions_file.jl) that contains all the functions that we need, that just remember to call it as follows:  
`include("functions_file.jl")`  
Than any of the functions here inside can be called and used.

# Arrays and matrices
At the following link, if needed, can be found additional information: https://www.matecdev.com/posts/julia-array-initialize.html  
So far, the most relevant information to know is given by the following example.  
Also arrays with different element type can be written.

In [ ]:
b1 = [4.0, 5, 6]                # 3-element Vector{Float64}
b2 = [4.0; 5; 6]                # 3-element Vector{Float64}
m1 = [4.0 5 6]                  # 1×3 Matrix{Float64}
A = [1 2 3; 4 5 6; 7 8 9]        # 3×3 Matrix{Int64}

println("b1 = $b1, b2 = $b2, m1 = $m1", " A = $A")

b1 = [4.0, 5.0, 6.0], b2 = [4.0, 5.0, 6.0], m1 = [4.0 5.0 6.0] A = [1 2 3; 4 5 6; 7 8 9]


In [35]:
[4, 5, 6]

3-element Vector{Int64}:
 4
 5
 6

In [36]:
[4 5 6]

1×3 Matrix{Int64}:
 4  5  6

In [37]:
[4; 5; 6]

3-element Vector{Int64}:
 4
 5
 6

In [38]:
[1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Even a similar way to the one-line function can be used to define arrays, in this case two syntaxes are possible, with different results:  
- []: in this case we define a vector;
- (): in this case we define a generator, the difference is that its memory is not already allocted, it will be only when needed, could be bettere performancing.

In [ ]:
vec = [(1/n)^2 for n in 1:100000]
x = sum(vec)

1.644924066898228

In [41]:
gen = ((1/n)^2 for n in 1:100000)
x = sum(gen)

1.6449240668982423

### Undefined vectors (matrices)
Vectors can also be defined without specifying their values, so, without filling them with 0 as in Matlab, but just allocate a portion of the memory and waiting for the filling phase. This save a bit of time instead of filling them with 0 or 1.  
The most used type are `Float64`, `int64` and `ComplexF64`.

In [2]:
n = 5
A1 = Array{Float64}(undef,n,n)          # 5×5 Matrix{Float64}
A2 = Matrix{Float64}(undef,n,n)         # 5×5 Matrix{Float64}

V1 = Array{Float64}(undef,n)            # 5-element Vector{Float64}
V2 = Vector{Float64}(undef,n)           # 5-element Vector{Float64}

A = Array{String}(undef,n)
A = Array{Int}(undef,n)

5-element Vector{Int64}:
         4194304
   1536065142792
   1536134143408
   1536080807600
 140716376883984

Also empty arrays can be initialized (without dimensions), the following example contains equivalent commands.  
It is ALWAYS better to specify the type of the data stored into a vector.

In [43]:
v = Array{Float64}(undef, 0); v = Float64[]; v = Vector{Float64}(undef, 0)
v = Any[]; v = Array{Any}(undef, 0); v = Vector{Any}(undef, 0); v = []

Any[]

Also function Matlab-style like `ones()`, `zeros()` and be used, also `rand()` that adopt the same filosophy of the previous two.  
To define an Identity matrix just type `I`, but a package is required.

In [51]:
using LinearAlgebra
mat = 5I + rand(3,3)
mat = I(3)

3×3 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

## The dot operator
To extend function that accept only scalar input to array input, just put a dot at the end of the function's name

In [55]:
x = [(2π/n) for n in 1:10]
y = sin.(x)
f(x) = 3x^3/(1+x^2)
z = f.(x)
# z = f(x) # this leads to an error

10-element Vector{Float64}:
 18.383886633134814
  8.55770151410267
  5.11671431742654
  3.353333929033819
  2.3082162000107957
  1.6431863658206738
  1.2015046969739323
  0.8989201052199165
  0.6862922515493683
  0.5335238620487099

In [56]:
# This two are equivalent
y = 2x.^2 + 3x.^5 - 2x.^8
y = @. 2x^2 + 3x^5 - 2x^8

10-element Vector{Float64}:
     -4.828671033653536e6
 -18039.263768983117
   -610.7857528421777
    -40.50500091388652
      0.12239075156841928
      3.0788623155395416
      2.5165970179806223
      1.8406756088311296
      1.3594357907060943
      1.0347659706787375

## Array indexing
Since the indexes of the arrays in julia can start also from negative values (the default is 1, as Matlab), to call the first and the last element of a vector is preferable to use the keywords `begin` and `end`.  
## Array slicing
See the example below.

In [57]:
A = rand(6,6)                   # 6×6 Matrix{Float64}
B = A[begin:2:end,begin:2:end]  # 3×3 Matrix{Float64}
C = A[1:2:5,1:2:5]              # Same as B

3×3 Matrix{Float64}:
 0.334943  0.230769  0.319854
 0.991663  0.205644  0.762805
 0.452046  0.676719  0.206799

## Logical indexing
Looking at the following example should be enough to understand the meaning and the way to use it. Note the necessity of using the dot operator for operations.

In [ ]:
A = rand(6,6)
A[ A .< 0.5 ] .= 0
print("A = $A")

A = [0.5758593873852039 0.0 0.6661484154975396 0.0 0.0 0.0; 0.8303551264151807 0.5679582131422078 0.9559971204703669 0.774566878617839 0.8496861624761051 0.0; 0.9799267013915215 0.7832457008929028 0.0 0.0 0.8754319522395653 0.5626690616548194; 0.0 0.0 0.8416432917664465 0.5440056281719026 0.682793637212791 0.9006420408395567; 0.6420901814429609 0.0 0.0 0.0 0.0 0.0; 0.732090518587796 0.0 0.7288924493192676 0.0 0.0 0.0]


In [ ]:
A = rand(6)
for i ∈ eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.8952252061705199
i=2 A[i]=0.8021659340553916
i=3 A[i]=0.04314958482892717
i=4 A[i]=0.6095741578881204
i=5 A[i]=0.3271679837892404
i=6 A[i]=0.8460011852063706


In [65]:
A = rand(6,6)
for i ∈ eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.09537156474792541
i=2 A[i]=0.0027236611793084453
i=3 A[i]=0.9618597284887679
i=4 A[i]=0.2274685427036348
i=5 A[i]=0.29497335031623184
i=6 A[i]=0.7137937710763594
i=7 A[i]=0.6879786839255004
i=8 A[i]=0.7287838840695937
i=9 A[i]=0.7484876541788851
i=10 A[i]=0.9758430616032329
i=11 A[i]=0.08326590782783994
i=12 A[i]=0.14513430254113058
i=13 A[i]=0.23478889608903686
i=14 A[i]=0.9347833567879398
i=15 A[i]=0.7031598839803592
i=16 A[i]=0.4590206888465864
i=17 A[i]=0.131194158394337
i=18 A[i]=0.20753979154194513
i=19 A[i]=0.06647190116707247
i=20 A[i]=0.6548485067963913
i=21 A[i]=0.7941140371800702
i=22 A[i]=0.08284377365780282
i=23 A[i]=0.2112442630415413
i=24 A[i]=0.6456172573292991
i=25 A[i]=0.03401978396507699
i=26 A[i]=0.7593475034151281
i=27 A[i]=0.1720236859604457
i=28 A[i]=0.920264814913247
i=29 A[i]=0.23423919721250885
i=30 A[i]=0.7016388610754603
i=31 A[i]=0.6645736771087408
i=32 A[i]=0.39598340624788475
i=33 A[i]=0.06307948753516324
i=34 A[i]=0.6622836093158107
i=35 A[i]=

In [66]:
A = rand(6,6)
for i ∈ 1:size(A,1), j ∈ 1:size(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.08199451874152675
i=1 j=2 A[i,j]=0.5333495906188863
i=1 j=3 A[i,j]=0.3815747736732601
i=1 j=4 A[i,j]=0.6156434184736557
i=1 j=5 A[i,j]=0.29653299630392493
i=1 j=6 A[i,j]=0.8898697271105654
i=2 j=1 A[i,j]=0.038163428803294375
i=2 j=2 A[i,j]=0.5697849857506454
i=2 j=3 A[i,j]=0.6583304162705064
i=2 j=4 A[i,j]=0.6415553648031175
i=2 j=5 A[i,j]=0.7125108775707996
i=2 j=6 A[i,j]=0.7241336216272968
i=3 j=1 A[i,j]=0.7626503588388537
i=3 j=2 A[i,j]=0.3485922761372462
i=3 j=3 A[i,j]=0.15313897140689436
i=3 j=4 A[i,j]=0.46702987925070494
i=3 j=5 A[i,j]=0.31453723933934474
i=3 j=6 A[i,j]=0.1846223595333758
i=4 j=1 A[i,j]=0.3943499804041536
i=4 j=2 A[i,j]=0.38513873446176217
i=4 j=3 A[i,j]=0.7715317821051808
i=4 j=4 A[i,j]=0.9958155709909351
i=4 j=5 A[i,j]=0.13519228371439818
i=4 j=6 A[i,j]=0.2119785378294301
i=5 j=1 A[i,j]=0.21641647649875484
i=5 j=2 A[i,j]=0.4369827957149012
i=5 j=3 A[i,j]=0.5494393609298728
i=5 j=4 A[i,j]=0.26725480269497737
i=5 j=5 A[i,j]=0.4840002008618681
i=5

Or can be used generic-array functions:

In [67]:
A = rand(6,6)
for i ∈ axes(A,1), j ∈ axes(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.3404165731129897
i=1 j=2 A[i,j]=0.07312665209695712
i=1 j=3 A[i,j]=0.7707503392295393
i=1 j=4 A[i,j]=0.6540533718814137
i=1 j=5 A[i,j]=0.059862886243675195
i=1 j=6 A[i,j]=0.4769812618925574
i=2 j=1 A[i,j]=0.6405279327781647
i=2 j=2 A[i,j]=0.2001219753016792
i=2 j=3 A[i,j]=0.9244228454607523
i=2 j=4 A[i,j]=0.07451304491241495
i=2 j=5 A[i,j]=0.19532262154010027
i=2 j=6 A[i,j]=0.982052327575118
i=3 j=1 A[i,j]=0.354865563005626
i=3 j=2 A[i,j]=0.7844290810936474
i=3 j=3 A[i,j]=0.8948799262067655
i=3 j=4 A[i,j]=0.5960267107810039
i=3 j=5 A[i,j]=0.08746055769324401
i=3 j=6 A[i,j]=0.8285651802680777
i=4 j=1 A[i,j]=0.6797548920592136
i=4 j=2 A[i,j]=0.9769539051071127
i=4 j=3 A[i,j]=0.6208565025285837
i=4 j=4 A[i,j]=0.7442783557719834
i=4 j=5 A[i,j]=0.7877300761150916
i=4 j=6 A[i,j]=0.06801742224540075
i=5 j=1 A[i,j]=0.13488272456997574
i=5 j=2 A[i,j]=0.3385274646827914
i=5 j=3 A[i,j]=0.36886212037390864
i=5 j=4 A[i,j]=0.981668289936363
i=5 j=5 A[i,j]=0.3247025163728432
i=5 j=6 

Other useful generic-array functions include:  
- `firstindex(A,dim)`;
- `lastindex(A,dim)`;
- `similar(Array{Float64}, axes(A))`.  

More information at https://docs.julialang.org/en/v1/devdocs/offset-arrays/


## Array operations
I don't even write the trivial things, such as matrix-matrix multiplication, matrix-vector multiplication, or elemt-wise multiplication (using the dot).  
A biyt more interesting is the dot product, performed by using the `dot` function as follows.


In [ ]:
v1 = rand(10)
v2 = rand(10)
dot_results = dot(v1,v2) # or equivalently, v1'v2
dot_results = v1'v2 # Matrix{Float64}

2.081222249752056

Also interesting there is the Matlab-style `\` operator, to solve linear systems in case of square matrix, or to find the least squares solution in case of rectangular matrices. NB: the matrix is always the first term

In [73]:
A = rand(3,3)                   # 3×3 Matrix{Float64}
b1 = [4.0, 5, 6]                # 3-element Vector{Float64}
b2 = [4.0; 5; 6]                # 3-element Vector{Float64}
m1 = [4.0 5 6]                  # 1×3 Matrix{Float64}

x=A\b1                          # Solves A*x=b
x=A\b2                          # Solves A*x=b  
# x=A\m1                          # Error!!

3-element Vector{Float64}:
 14.241654545338518
 -3.5451838266229636
  5.40710282835447

## Concatenations
all the informations about concatenations are reported here https://www.matecdev.com/posts/julia-array-resize-concatenate.html  
## Data structures
the same for structures https://www.matecdev.com/posts/julia-basic-data-structures.html
## Plots
the same for plots https://www.matecdev.com/posts/julia-plotting.html